In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("insurance.csv")

data.head()

,age,sex,bmi,children,smoker,region,charges,friends,enemies,chips,fries,ramen,toportyu
0,19,female,NaN,0,yes,southwest,16884.92400,5,3,7,5,3,6
1,18,male,33.770,1,no,southeast,1725.55230,0,1,4,4,4,3
2,28,male,33.000,3,no,southeast,4449.46200,9,3,5,2,1,3
3,33,male,22.705,0,no,northwest,21984.47061,5,10,4,3,2,4
4,32,male,28.880,0,no,northwest,3866.85520,4,3,4,4,1,7

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1327 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
 7   friends   1338 non-null   int64
 8   enemies   1338 non-null   int64
 9   chips     1338 non-null   int64
 10  fries     1338 non-null   int64
 11  ramen     1338 non-null   int64
 12  toportyu  1338 non-null   int64
dtypes: float64(2), int64(8), object(3)
memory usage: 136.0+ KB

In [4]:
d_types = dict(data.dtypes)
for name , type_ in d_types.items():
    if str(type_) == 'object':
        print(f"<======== {name} ===========>")
        print(data[name].value_counts())
        print()

<======== sex ===========>
male      676
female    662
Name: sex, dtype: int64

<======== smoker ===========>
no     1064
yes     274
Name: smoker, dtype: int64

<======== region ===========>
southeast    360
southwest    324
northwest    324
northeast    320
middle        10
Name: region, dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder

for name , type_ in d_types.items():
    if str(type_) == 'object':
        Le = LabelEncoder()
        data[name] = Le.fit_transform(data[name])

In [6]:
from sklearn.preprocessing import OneHotEncoder

onehotencoder = OneHotEncoder()
part = onehotencoder.fit_transform(data['region'].values.reshape(-1,1)).toarray()

values = dict(data["region"].value_counts())

for e , (val , _) in enumerate(values.items()):
    data["region_" + str(val)] = part[:,e]

data = data.drop(["region"] , axis = 1)

data.head()

,age,sex,bmi,children,smoker,charges,friends,enemies,chips,fries,ramen,toportyu,region_3,region_4,region_2,region_1,region_0
0,19,0,NaN,0,1,16884.92400,5,3,7,5,3,6,0.0,0.0,0.0,0.0,1.0
1,18,1,33.770,1,0,1725.55230,0,1,4,4,4,3,0.0,0.0,0.0,1.0,0.0
2,28,1,33.000,3,0,4449.46200,9,3,5,2,1,3,0.0,0.0,0.0,1.0,0.0
3,33,1,22.705,0,0,21984.47061,5,10,4,3,2,4,0.0,0.0,1.0,0.0,0.0
4,32,1,28.880,0,0,3866.85520,4,3,4,4,1,7,0.0,0.0,1.0,0.0,0.0

In [10]:
from scipy import stats 

col_cox , lam = stats.boxcox(data["expenses"])[0:2]
print("Skewness in Column : Sqrt Expenses " ,pd.Series(col_cox).skew())

plt.hist(col_cox)
plt.show()

KeyError: 'expenses'

In [11]:
data["expenses"] = col_cox

NameError: name 'col_cox' is not defined

In [ ]:
remaining_columns = list(data.columns)
remaining_columns.remove("expenses")

In [ ]:
X = data[remaining_columns].values 
Y = data['expenses'].values

In [ ]:
from sklearn.model_selection import train_test_split

Xtrain , Xtest , Ytrain , Ytest = train_test_split(X , Y , test_size = 0.2 , random_state = 4)

In [ ]:
from sklearn.linear_model import Ridge , Lasso , ElasticNet , LinearRegression

In [ ]:
model = LinearRegression()
model.fit(Xtrain , Ytrain)
print(" Training Accuracy : " , model.score(Xtrain , Ytrain))
print(" Testing Accuracy : " , model.score(Xtest , Ytest))

 Training Accuracy :  0.7749547304018276
 Testing Accuracy :  0.7497079440424593

In [ ]:
model = Ridge()
model.fit(Xtrain , Ytrain)
print(" Training Accuracy : " , model.score(Xtrain , Ytrain))
print(" Testing Accuracy : " , model.score(Xtest , Ytest))

 Training Accuracy :  0.7749377189073672
 Testing Accuracy :  0.7502904376174966

In [ ]:
model = Lasso()
model.fit(Xtrain , Ytrain)
print(" Training Accuracy : " , model.score(Xtrain , Ytrain))
print(" Testing Accuracy : " , model.score(Xtest , Ytest))

 Training Accuracy :  0.2589359547500544
 Testing Accuracy :  0.2841101128580017

In [ ]:
# Elastic 

# lambda_1*L1 + lambda_2*L2 
# alpha = lambda_1 + lambda_2 , l1_ratio = lambda_1/(lambda_1 + lambda_2)

model = ElasticNet()
model.fit(Xtrain , Ytrain)
print(" Training Accuracy : " , model.score(Xtrain , Ytrain))
print(" Testing Accuracy : " , model.score(Xtest , Ytest))

 Training Accuracy :  0.26553917703322805
 Testing Accuracy :  0.2906976260872922

Changing Parameter for Lasso and ElasticNet

In [ ]:
model = Lasso(alpha = 0.01)
model.fit(Xtrain , Ytrain)
print(" Training Accuracy : " , model.score(Xtrain , Ytrain))
print(" Testing Accuracy : " , model.score(Xtest , Ytest))

 Training Accuracy :  0.7733046323058576
 Testing Accuracy :  0.7516010885977982

In [ ]:
# Elastic 

# lambda_1*L1 + lambda_2*L2 
# alpha = lambda_1 + lambda_2 , l1_ratio = lambda_1/(lambda_1 + lambda_2)

model = ElasticNet(alpha = 0.01 + 0.01 , l1_ratio = 0.01/(0.01 + 0.01))
model.fit(Xtrain , Ytrain)
print(" Training Accuracy : " , model.score(Xtrain , Ytrain))
print(" Testing Accuracy : " , model.score(Xtest , Ytest))

 Training Accuracy :  0.7698503985770702
 Testing Accuracy :  0.7531054985757829